// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtraffic_light.cpp"
#include "Vtraffic_light___024root__DepSet_h1079e0a9__0.cpp"
#include "Vtraffic_light___024root__DepSet_hd5da33b1__0.cpp"
#include "Vtraffic_light__Trace__0.cpp"
#include "Vtraffic_light__ConstPool_0.cpp"
#include "Vtraffic_light___024root__Slow.cpp"
#include "Vtraffic_light___024root__DepSet_h1079e0a9__0__Slow.cpp"
#include "Vtraffic_light___024root__DepSet_hd5da33b1__0__Slow.cpp"
#include "Vtraffic_light__Syms.cpp"
#include "Vtraffic_light__Trace__0__Slow.cpp"
#include "Vtraffic_light__TraceDecls__0__Slow.cpp"
